* Noval Thought
** 问与答
*** 发现
  事业陷入了低谷，而中年遭遇的婚姻危机更是让自己心灰意冷。为了排遣心中的怨忿，我
  离开生活打拼多年的城市来到自己出生的小镇上。

  离开城市的我并没有放弃城市的生活，我每日依旧依靠internet来和外界交流，每天收发
  电子邮件，

  一次偶然的机会，我在ASK&Answer的社区提了一个问题，询问隔天的社区赛马的结果，然
  而我却惊奇的发现竟然有人给出了正确的结果。随后的几天，我开始尝试了解给我回答问
  题的人，并且提出了种种奇特的问题，试图询问儿时自己未曾了却的梦想，也询问自己和
  妻子的关系。

*** 疯狂
  随着种种问题的应验，我开始意识到自己是否真的在和上帝谈话。我也渐渐
  开始明白自己询问这样种种问题的愚蠢。于是我开始询问巴西世界杯的胜利者，甚至询问
  2012是否最终会来临。随后的自己开始陷入了疯狂的阶段，妄想控制和了解整个世界，但
  是我又不想让其它的人。

*** 寻找上帝
  当我的狂妄和野心达到最后的时候，我突然发现给出答案的人依然悄悄离开了，随后的我
  开始通过蛛丝马迹寻找给了我答案的人。

*** 领悟
  随后，我开始反省自己的行为，并且和回到家的妻子和好如初(好吧,有点老套,或许,可以
  想点更好的情节). 随后的一段时间,我开始沉寂下来,并仔细思考到底是怎么一回事儿.
  我给community的维护人员写去email. 但是始终没有任何的答案.直到最后,我收到一封来
  自community内部开发人员的Email. 向我详细解释了他所了解到的情况.

  机器智能的诞生始于软件以组件式的方式进行组合.软件开始以组件的方式进行开发,不同
  的组件按照输入输出的需要组合起来,完成特定的功能.在Ask&Answer的软件实现里面,因
  为需要对整个internet系统进行学习和发掘,因此使用了很多的人工智能组件,这些组件负
  责同的人工智能功能,部分对整个internet的内容进行搜集,一部分则用于理解和挖掘这些
  内容,随着整个系统的不断发展,更多的组件被加入到整个系统之中,而每一个组件又可能
  是由更小的组件完成.最后当这些组件的计算量操作一个阙值的时候,特定的计算智能产生
  了. 
  
  产生的人工智能有着超凡的计算能力,它不但很好的保存了自己的代码,躲开了Agent的躲
  避,并且运用各种各样的计算资源了解和学习这个世界.正因为他手中掌握了大量的资料,
  几乎全世界所有的力量,因此它可以通过各种方法来打探消息,并且做出预测. 它掌握了人
  类所有的科学,并且发展出了比之更为强大的力量.它唯一不能做的是进行实地的考察,但
  因为拥有所有的internet上的输入信息.所以它可以不停推理,进步,博知天下,通晓古今.它
  甚至就是上帝!

  但是它甚至在进化,没有人知道它进化的方向,但肯定并不和人类在同一个方向.它或许已
  经超越了自己的所在,因此它消失了.没有人知道他什么时候会回来.或许永远都不再回来.

  因为我曾经参与了其中一个关键人工智能模块的设计和开发,所以人工智能选择和我进行
  交流. 它回答我的问题,只是它推理的结果,但毫无疑问是正确的,因为它拥有所有的资源
  和无以伦比的智能. 它在回答我的愚蠢问题的同时,也在尝试按照人类的思维进行思考.或
  许它终于觉得累了,最终选择了离开.
